version: '3'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: voyai
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  backend:
    build: .
    command: node backend/index.js
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/voyai
  frontend:
    build: .
    command: npm run dev --prefix frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend